services:
  builder:
    build: .
    volumes:
      - ./data/:/data/
      - ./output:/output/
      - cache:/root/.cache/Tectonic/
    environment:
      - BUILDER_PRINT_TO_STDOUT=false
volumes:
  cache: {}

