{{personal}}

general:
  company:
    name: STEMCO # The company name, obviously...
    purpose: 'making the roads safer' # A company goal that might be included

recipient:
  position: Human Resources

job:
  title: Mechanical Engineering Co-Op # Job title
  whoami: generic # [generic|custom]
  source: heard # [generic|web|indeed|heard|custom]
  interest: generic # [generic|custom] How you're interested
  fit: generic # [generic|custom] How you think you'd be as a fit for this job
  fit_cause: generic # [generic|focus_cs_mech|focus_elec_mech|focus_detail|focus_hands_on|custom|none] Avoid generic and none! Choose one, add one, or strongly consider going with custom.
  value_add: company # [generic|company|skills|company_skills|custom|none]

body:
  - >
    Paragraph 2
  - >
    Paragraph 3
  - >
    Paragraph 4