{{ template "personal.yaml" . }}

process: false

target: template_resume.tex

output_name: Resume

theme:
  accent: 0,0,0
  accentlight: 0,0,0
  title: 0,0,0
  titlegap: \medskip
  icons: true
  qrcode: false

engineering:
  label: Engineering Experience

work:
  label: Work Experience
  entries:
    - role: Technical Services Engineer
      company: Epic Systems Corporation
      from: August 2022
      to: Present
      url: https://epic.avature.net/Careers/FolderDetail/Technical-Solutions-Engineer/742
      description: >
        Supported 6 clients in the successful operation of the Epic Population Health suite (Healthy Planet).
        Support work involved customer facing root cause analysis on technical problems, acting as liaison with interal R\&D teams to develop solution as required, and driving customers to be successful in the broader adoption of the software suite.
        Additionally led an internal initiative to improve broad adoption of product features, developed searches to determine patient level data correction, and acted as subject matter expert for cardiology and diabetes predictive models.

    - role: Teaching and Grading Assistant
      company: LETU
      from: Fall 2020
      to: Fall 2021
      description: >
        Teaching assistant for IEP 1 Lab, involving educating students in basic basic assembly techniques and diagnosing and solving problems that appeared during assembly, including troubleshooting FDM 3D printers.
        Grading assistant for IEP 1 Graphics Lab using SolidWorks.
    - role: Machinist and Welder
      company: Rouge Machining
      from: March 2018
      to: December 2021
      description: >
        Fabricated tube steel table frames, produced and worked on components for lead shields for the nuclear industry in Oak Ridge, TN.
        Designed, marketed, and manufactured accessories for mechanical keyboards during downtime.

education:
  school:
    label: Education
    entries:
      - program: Mechanical Engineering, B.S. (BSME)
        school: LeTourneau University
        gpa: 3.54/4.0 (Cum Laude, Dean's List Fall 2018, President's List Spring 2020)
        from: May 2022

projects:
  label: Projects
  entries:
    - name: LEGRange (Senior Design)
      company: LETU
      url: https://letu.edu/academics/engineering/nathan_green_senior_design_team.html
      from: Fall 2021
      to: Spring 2022
      description: >
        Participating in mechanical design for electronics housing, and SDR development and modification for GPS transmission purposes (using C++).
        Existing software interprets sampled radio signals and reads GPS data.
        Primary tasking involves implementing rogue signal generation in software given timing and performance constraints.
    - name: Freshman Project Design Team
      location: LeTourneau University (LETU)
      from: Fall 2020
      to: Fall 2021
      description: >
        Led design project for the 2021 Introduction to Engineering Practices 1 (IEP 1) class.
        Design involved PCB layout, SolidWorks modelling, and Arduino integration and programming.
        Production run of 185 units were sourced and kits collected.
    - name: Home Assistant MQTT IOT
      location: Personal
      url: https://github.com/W-Floyd/ha-mqtt-iot
      description: >
        Open source software that provides a MQTT client to interface with HomeAssistant, a home automation software suite.
        This tool allows creating arbitrary sensors, switches, lights, etc. based on locally run commands, or builtin routines.
        Programmed in Golang.
      from: October 2020 
      to: Present
    - name: ClickBait
      location: LETU
      url: https://notmy.space/2020/03/clickbait/
      description: >
        Led an engineering project to create a battery powered automatic fishing caster intended for disabled users, as part of Project Management, Design, and Entrepreneurship.
      from: Fall 2019
    - name: Pen Plotter
      location: LETU
      url: https://notmy.space/2021/12/pen-plotter/
      description: >
        For IEP 2 class, designed from scratch a low cost (\$20) CNC pen plotter, including 3D printed hardware and custom GCode parser.
      from: Spring 2019

leadership:
  label: Leadership Experience

skills:
  label: Technical Skills
  entries:
    - category: Office
      entries:
        - Microsoft Office suite
        - Outlook macros
        - Outlook rules
        - Autohotkey macros
    - category: CAD/3D Modeling
      entries:
        - SolidWorks
        - OpenSCAD
        - Blender
        - KiCAD
    - category: Programming
      entries:
        - Golang
        - Bash scripting
        - SQL queries
        - C++
        - Octave/MATLAB
        - LabVIEW
    - category: Software Development
      entries:
        - Git
        - Arduino/PlatformIO
        - MQTT
        - Appsmith
        - Airtable/NocoDB
    - category: Linux Systems
      entries:
        - System administration
        - Debian
        - Arch
        - Docker
        - Package maintenance
    - category: Multimedia
      entries:
        - Inkscape
        - Photoshop
        - After Effects
        - LaTeX
    - category: Fabrication
      entries:
        - Welding (MIG, stick)
        - Lathing
        - Milling
    - category: Prototyping
      entries:
        - 3D Printing (FDM)
        - Soldering
        - Electronics Design
        - Basic PCB layout

activities:
  label: Activities and Achievements
  entries:
    - title: Open Source
      
      description: >
        Participates in various open source projects, including software and graphic design