{{ template "personal.yaml" . }}

process: true

target: template_resume_new.tex

output_name: William Floyd

theme:
  accent: 0,0,0
  accentlight: 0,0,0
  title: 0,0,0
  titlegap: \medskip
  icons: true
  qrcode: false

sections:
  - entries:
      - title: Mechanical Engineering, B.S. (BSME)
        subtitle: LeTourneau University
        description: 3.54/4.0 (Cum Laude, Dean's List Fall 2018, President's List Spring 2020)
        from: May 2022
  - label: Work Experience
    entries:
      - title: Technical Services Engineer
        subtitle: Epic Systems Corporation
        from: Aug 2022
        to: Present
        description: >
          Supported 6 clients in the successful operation of the Epic Population Health suite (Healthy Planet).
          Support work involved customer facing root cause analysis on technical problems, acting as liaison with interal R\&D teams to develop solution as required, and driving customers to be successful in the broader adoption of the software suite.
          Additionally led an internal initiative to improve broad adoption of product features, developed searches to determine patient level data correction, and acted as subject matter expert for cardiology and diabetes predictive models.
      - title: Teaching and Grading Assistant
        subtitle: LETU
        from: Fall 2020
        to: Fall 2021
        description: >
          Teaching assistant for IEP 1 Lab, involving educating students in basic basic assembly techniques and diagnosing and solving problems that appeared during assembly, including troubleshooting FDM 3D printers.
          Grading assistant for IEP 1 Graphics Lab using SolidWorks.
      - title: Machinist and Welder
        subtitle: Rouge Machining
        from: Mar 2018
        to: Dec 2021
        description: >
          Fabricated tube steel table frames, produced and worked on components for lead shields for the nuclear industry in Oak Ridge, TN.
          Designed, marketed, and manufactured accessories for mechanical keyboards during downtime.
  - label: Projects
    entries:
      - title: LEGRange (Senior Design)
        subtitle: LETU
        url: https://letu.edu/academics/engineering/nathan_green_senior_design_team.html
        from: Fall 2021
        to: Spring 2022
        description: >
          Participating in mechanical design for electronics housing, and SDR development and modification for GPS transmission purposes (using C++).
          Existing software interprets sampled radio signals and reads GPS data.
          Primary tasking involves implementing rogue signal generation in software given timing and performance constraints.
      - title: Freshman Project Design Team
        subtitle: LeTourneau University (LETU)
        from: Fall 2020
        to: Fall 2021
        description: >
          Led design project for the 2021 Introduction to Engineering Practices 1 (IEP 1) class.
          Design involved PCB layout, SolidWorks modelling, and Arduino integration and programming.
          Production run of 185 units were sourced and kits collected.
      - title: Home Assistant MQTT IOT
        subtitle: Personal
        url: https://github.com/W-Floyd/ha-mqtt-iot
        description: >
          Open source software that provides a MQTT client to interface with HomeAssistant, a home automation software suite.
          This tool allows creating arbitrary sensors, switches, lights, etc. based on locally run commands, or builtin routines.
          Programmed in Golang.
        from: Oct 2020 
        to: Present
      - title: ClickBait
        subtitle: LETU
        url: https://notmy.space/2020/03/clickbait/
        description: >
          Led an engineering project to create a battery powered automatic fishing caster intended for disabled users, as part of Project Management, Design, and Entrepreneurship.
        from: Fall 2019
      - title: Pen Plotter
        subtitle: LETU
        url: https://notmy.space/2021/12/pen-plotter/
        description: >
          For IEP 2 class, designed from scratch a low cost (\$20) CNC pen plotter, including 3D printed hardware and custom GCode parser.
        from: Spring 2019
  - label: Technical Skills
    newpage: true
    entries:
      - lefttext: Office
        entries:
          - Microsoft Office suite
          - Outlook macros
          - Outlook rules
          - Autohotkey macros
      - lefttext: CAD/3D Modeling
        entries:
          - SolidWorks
          - OpenSCAD
          - Blender
          - KiCAD
      - lefttext: Programming
        entries:
          - Golang
          - Bash scripting
          - SQL queries
          - C++
          - Octave/MATLAB
          - LabVIEW
      - lefttext: Development
        entries:
          - Git
          - Arduino/PlatformIO
          - MQTT
          - Appsmith
          - Airtable/NocoDB
          - Postgres
          - Metabase
      - lefttext: Linux Systems
        entries:
          - System administration
          - Debian
          - Arch
          - Docker
          - Package maintenance
      - lefttext: Multimedia
        entries:
          - Inkscape
          - Photoshop
          - After Effects
          - LaTeX
      - lefttext: Fabrication
        entries:
          - Welding (MIG, stick)
          - Lathing
          - Milling
      - lefttext: Prototyping
        entries:
          - 3D Printing (FDM)
          - Soldering
          - Electronics Design
          - Basic PCB layout
  - label: Activities and Achievements
    disable: true
    entries:
    - title: Open Source
      description: Participates in various open source projects, including software and graphic design