name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - run: cd builder && go build -o builder . && cd ../
    - run: wget "https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic@0.14.1/tectonic-0.14.1-x86_64-unknown-linux-musl.tar.gz" -O 'tectonic.tar.gz'
    - run: tar -xf 'tectonic.tar.gz'
    - run: rm 'tectonic.tar.gz'
    - run: ./builder/build.sh 'William Floyd'
    - uses: actions/upload-artifact@v3
      with:
        name: Resume
        path: output/William Floyd.pdf
    - uses: andreaswilli/delete-release-assets-action@<version>
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: release
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output/*.pdf
        file_glob: true
        tag: release
        release_name: Release
        overwrite: true
        target_commit: release
        body: Auto built resume